# Generated by Claude Sonnet 4.6 on 2026-05-14
# Sanitize-HtmlRef.ps1
# Anonymizes ManaTime HTML reference files for safe git publishing.
# Replaces personal/company data with deterministic fakes while keeping
# form structure and JS call shapes used by client code for page detection.
#
# Behavior:
#   First run  : backs up <file> to <file>.orig, writes sanitized to <file>
#   Subsequent : re-sanitizes from <file>.orig into <file> (idempotent)
#   .gitignore *.html.orig to keep originals out of version control
#
# Usage: ./ref/Sanitize-HtmlRef.ps1 ref/                                 # whole ref dir
#        ./ref/Sanitize-HtmlRef.ps1 ref/presences/                       # subdirectory
#        ./ref/Sanitize-HtmlRef.ps1 ref/presences/create/advanced.html   # single file
#        ./ref/Sanitize-HtmlRef.ps1 ref/presences/ ref/other/file.html   # mixed

[CmdletBinding()]
param(
    [Parameter(Mandatory, ValueFromRemainingArguments)]
    [string[]] $Files
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Script-level state reset per file (accessible from nested scriptblocks)
$script:IdMap  = $null
$script:NextId = 0

function Get-MappedId([string] $realId) {
    if (-not $realId) { return $realId }
    if (-not $script:IdMap.Contains($realId)) {
        $script:IdMap[$realId] = $script:NextId++
    }
    return [string]$script:IdMap[$realId]
}

function Invoke-HtmlAnonymization([string] $html) {

    # Reset ID state for each file so output is deterministic
    $script:IdMap  = [ordered]@{}
    $script:NextId = 10001

    # Seed the ID map in document order so every run produces the same mapping
    [regex]::Matches($html, 'value="(\d{4,})"')      | ForEach-Object { $null = Get-MappedId $_.Groups[1].Value }
    [regex]::Matches($html, "user_id=(\d+)")          | ForEach-Object { $null = Get-MappedId $_.Groups[1].Value }
    [regex]::Matches($html, "'orgId',\s*""(\d+)""")   | ForEach-Object { $null = Get-MappedId $_.Groups[1].Value }
    [regex]::Matches($html, "company_id:\s*'(\d+)'")  | ForEach-Object { $null = Get-MappedId $_.Groups[1].Value }

    # ── 1. User <select> options ────────────────────────────────────────────
    # Anonymize display name and numeric ID; preserve selected="selected"
    $script:UserIndex = 0
    $html = [regex]::Replace($html,
        '(?s)(<select\b[^>]+\bid="create_user"[^>]*>)(.*?)(</select>)',
        {
            param($m)
            $script:UserIndex = 0
            $inner = [regex]::Replace($m.Groups[2].Value,
                '<option\s+value="(\d+)"(\s+selected="selected")?>([^<]*)</option>',
                {
                    param($o)
                    $script:UserIndex++
                    $fakeId = Get-MappedId $o.Groups[1].Value
                    "<option value=`"$fakeId`"$($o.Groups[2].Value)>User $($script:UserIndex)</option>"
                })
            "$($m.Groups[1].Value)$inner$($m.Groups[3].Value)"
        })

    # ── 2. Task <select>: optgroup labels and activity options ──────────────
    # Empty option (value="") is kept untouched
    $script:ActIndex = 0
    $script:GrpIndex = 0
    $html = [regex]::Replace($html,
        '(?s)(<select\b[^>]+\bid="create_task"[^>]*>)(.*?)(</select>)',
        {
            param($m)
            $script:ActIndex = 0
            $script:GrpIndex = 0
            $inner = $m.Groups[2].Value

            $inner = [regex]::Replace($inner,
                '(<optgroup\s+label=")[^"]+(")',
                {
                    param($o)
                    $script:GrpIndex++
                    "$($o.Groups[1].Value)Group $($script:GrpIndex)$($o.Groups[2].Value)"
                })

            # value may be a plain integer ("9561") or a composite ("16476***1634")
            # match any non-empty value; remap every numeric component via the ID map
            $inner = [regex]::Replace($inner,
                '<option\s+value="([^"]+)">([^<]*)</option>',
                {
                    param($o)
                    $script:ActIndex++
                    $fakeVal = [regex]::Replace($o.Groups[1].Value, '\d+',
                        { param($n) Get-MappedId $n.Value })
                    "<option value=`"$fakeVal`">Activity $($script:ActIndex)</option>"
                })

            "$($m.Groups[1].Value)$inner$($m.Groups[3].Value)"
        })

    # ── 3. GTM container ID ─────────────────────────────────────────────────
    $html = [regex]::Replace($html, 'GTM-[A-Z0-9]+', 'GTM-XXXXXXX')

    # ── 4. Amplitude API key ────────────────────────────────────────────────
    $html = [regex]::Replace($html,
        "(amplitude\.init\(')[0-9a-f]{32}(')",
        '$1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$2')

    # ── 5. amplitude.setGroup orgId ─────────────────────────────────────────
    $html = [regex]::Replace($html,
        "(amplitude\.setGroup\('orgId',\s*"")(\d+)("")",
        { param($m) "$($m.Groups[1].Value)$(Get-MappedId $m.Groups[2].Value)$($m.Groups[3].Value)" })

    # ── 6. identifyEvent personal data block ────────────────────────────────
    # Replace everything from the Identify() constructor to amplitude.identify()
    # Keeps the call structure intact for documentation; scrubs all real values
    $html = [regex]::Replace($html,
        '(?s)(const identifyEvent\s*=\s*new amplitude\.Identify\(\);).*?(amplitude\.identify\(identifyEvent\);)',
        {
            param($m)
            $stub  = "        identifyEvent.set('userId', '10001');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('email', 'user@example.com');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('name', 'User 1');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('firstName', 'User');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('lastName', '1');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('gender', '');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('birthday', '2000-01-01');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('address', {street: '', postalCode: '', city: '', country: 'XX'});" + [Environment]::NewLine
            $stub += "        identifyEvent.set('company', {id: '10002', name: 'Company', employee_count: '0', plan: ''});" + [Environment]::NewLine
            $stub += "        identifyEvent.setOnce('createdAt', '2000-01-01T00:00:00+00:00');" + [Environment]::NewLine
            $stub += "        identifyEvent.set('language', 'fr');" + [Environment]::NewLine
            "$($m.Groups[1].Value)`n$stub        $($m.Groups[2].Value)"
        })

    # ── 7. amplitude.track("Presence") company data ─────────────────────────
    $html = [regex]::Replace($html,
        '(?s)(amplitude\.track\("Presence",\s*\{).*?(\}\);)',
        ('$1' +
            'plan: "", employees: 0, country: "XX", ' +
            'company_id: "10002", company_name: "Company", ' +
            'role_is_admin: "false", role_is_hr: "false", role_is_manager: "false", ' +
            'role_is_export: "false", role_is_planning: "false", ' +
            'role_is_validator: "false", role_is_user: "true"' +
            '$2'))

    # ── 8. Sentry DSN ───────────────────────────────────────────────────────
    $html = [regex]::Replace($html,
        "(dsn:\s*')[^']+(')",
        '$1https://00000000000000000000000000000000@sentry.io/0000000$2')

    # ── 9. Sentry.setUser payload ───────────────────────────────────────────
    # Keep the call so CheckPage can still find it; scrub username and roles
    $html = [regex]::Replace($html,
        '(Sentry\.setUser\()(\{[^}]+\})(\);)',
        '$1{"username":"user@example.com","roles":["ROLE_USER"]}$3')

    # ── 10. forms.office.com URL (hash + all query params) ──────────────────
    # Replaces the form hash, user_id, company_id, and user_email params
    $html = [regex]::Replace($html,
        '(forms\.office\.com/r/)[A-Za-z0-9]+(\?[^"]*)',
        {
            param($m)
            $query = [regex]::Replace($m.Groups[2].Value,
                '(user_id=)(\d+)',
                { param($q) "$($q.Groups[1].Value)$(Get-MappedId $q.Groups[2].Value)" })
            $query = [regex]::Replace($query,
                '(company_id=)(\d+)',
                { param($q) "$($q.Groups[1].Value)$(Get-MappedId $q.Groups[2].Value)" })
            $query = [regex]::Replace($query,
                '(user_email=)[^"&\s]+',
                '$1user%40example.com')
            "$($m.Groups[1].Value)XXXXXXXXXXXXXXXX$query"
        })

    # ── 11. Nav bar profile: name and company display spans / headings ───────
    $html = [regex]::Replace($html,
        '(<span\s[^>]*\bclass="[^"]*\bname\b[^"]*"[^>]*>)[^<]*(</span>)',
        '$1User 1$2')
    $html = [regex]::Replace($html,
        '(<span\s[^>]*\bclass="[^"]*\bcompany\b[^"]*"[^>]*>)[^<]*(</span>)',
        '$1Company$2')
    # <h4> and <h5 class="text-muted"> in the profile dropdown
    $html = [regex]::Replace($html,
        '(?s)(<h4>)[^<]+(</h4>)',
        '$1User 1$2')
    $html = [regex]::Replace($html,
        '(?s)(<h5\s[^>]*class="text-muted"[^>]*>)[^<]+(</h5>)',
        '$1Company$2')

    # ── 12. Disable script execution ────────────────────────────────────────
    # Primary: inject CSP meta tag as first child of <head> — blocks all scripts
    # and external fetches regardless of how many script tags exist.
    $html = [regex]::Replace($html,
        '(<head\b[^>]*>)',
        '$1<meta http-equiv="Content-Security-Policy" content="default-src ''none''">')
    # Belt-and-suspenders: flip every script tag type to text/plain so browsers
    # skip both execution and external src= fetching, even before CSP is parsed.
    $html = [regex]::Replace($html,
        '<script\b([^>]*?)(?:\s+type="[^"]*")?>',
        '<script$1 type="text/plain">')

    # ── 13. Remaining value="REAL_ID" attributes not already replaced ───────
    # Targets only value="" attributes to avoid clobbering script content
    foreach ($realId in @($script:IdMap.Keys)) {
        $fakeId = [string]$script:IdMap[$realId]
        if ($realId -ne $fakeId) {
            $html = [regex]::Replace($html,
                "(?<=value="")$([regex]::Escape($realId))(?="")",
                $fakeId)
        }
    }

    return $html
}

$expandedFiles = foreach ($rawPath in $Files) {
    $resolved = Resolve-Path $rawPath -ErrorAction SilentlyContinue
    if (-not $resolved) {
        Write-Warning "Not found: $rawPath"
        continue
    }
    if (Test-Path $resolved -PathType Container) {
        Get-ChildItem -Path $resolved -Recurse -Filter '*.html' |
            Where-Object { $_.Name -notlike '*.orig' } |
            Select-Object -ExpandProperty FullName
    } else {
        [string]$resolved
    }
}

foreach ($file in $expandedFiles) {

    if ($file.EndsWith('.orig', [System.StringComparison]::OrdinalIgnoreCase)) {
        Write-Warning "Skipping .orig file directly: $file"
        continue
    }

    $origFile = "$file.orig"

    if (Test-Path $origFile) {
        Write-Verbose "Re-sanitizing from backup: $origFile"
        $source = $origFile
    } else {
        Write-Verbose "Creating backup: $origFile"
        Copy-Item $file $origFile
        $source = $origFile
    }

    $raw  = [System.IO.File]::ReadAllText($source, [System.Text.Encoding]::UTF8)
    $anon = Invoke-HtmlAnonymization $raw
    [System.IO.File]::WriteAllText($file, $anon, [System.Text.Encoding]::UTF8)
    Write-Host "Sanitized: $file"
}
