// Generated by Claude, 2026-05-18
namespace Mynatime.CLI;

using Mynatime.Client;
using Mynatime.Domain;
using Mynatime.Infrastructure;
using Mynatime.Infrastructure.ProfileTransaction;
using Newtonsoft.Json.Linq;
using Spectre.Console;
using System.Globalization;

internal static class ActivityRenderer
{
    /// <summary>
    /// Builds an <see cref="ActivityStartStopManager"/> from all transaction items in <paramref name="profile"/>.
    /// Finds the <see cref="ActivityStartStop"/> item (or uses an empty one), feeds every
    /// <see cref="NewActivityItemPage"/> item into <see cref="ActivityStartStopManager.ExtraActivities"/>,
    /// calls GenerateItems, and returns the manager.
    /// When <paramref name="sourceMap"/> is provided, each (transactionItem → wrapper) pair for
    /// NewActivityItemPage items is recorded so callers can identify which wrapper came from which
    /// transaction item by reference.
    /// </summary>
    internal static ActivityStartStopManager LoadActivities(
        MynatimeProfile profile,
        IDictionary<JObject, ActivityItemWrapper>? sourceMap = null)
    {
        var state = new ActivityStartStop();

        if (profile.Transaction != null)
        {
            foreach (var item in profile.Transaction.Items)
            {
                if (MynatimeProfileTransactionManager.Default.OfClass<ActivityStartStop>(item))
                {
                    state = new ActivityStartStop(item);
                    break;
                }
            }
        }

        var manager = new ActivityStartStopManager(state);

        if (profile.Transaction != null)
        {
            foreach (var item in profile.Transaction.Items)
            {
                if (MynatimeProfileTransactionManager.Default.OfClass<NewActivityItemPage>(item))
                {
                    var page = (NewActivityItemPage)MynatimeProfileTransactionManager.Default.GetInstanceOf(item);
                    var wrapper = new ActivityItemWrapper(page);
                    manager.ExtraActivities.Add(wrapper);
                    sourceMap?.Add(item.Element, wrapper);
                }
            }
        }

        manager.GenerateItems();
        return manager;
    }

    /// <summary>
    /// Prints manager errors in red and warnings in yellow.
    /// </summary>
    internal static void WriteManagerDiagnostics(IAnsiConsole console, ActivityStartStopManager manager)
    {
        if (manager.Errors.Any())
        {
            console.MarkupLine("[red]Errors:[/]");
            foreach (var error in manager.Errors)
            {
                console.MarkupLine("[red]- " + Markup.Escape(error.ToString()) + "[/]");
            }
        }

        if (manager.Warnings.Any())
        {
            console.MarkupLine("[yellow]Warnings:[/]");
            foreach (var warning in manager.Warnings)
            {
                console.MarkupLine("[yellow]- " + Markup.Escape(warning.ToString()) + "[/]");
            }
        }
    }

    /// <summary>
    /// Renders a Spectre.Console table of activities.
    /// When <paramref name="filter"/> is provided, rows where it returns false are skipped.
    /// When <paramref name="annotate"/> is provided, a leading annotation column is added; the
    /// function returns markup for each row's cell (empty string = blank cell).
    /// </summary>
    internal static void WriteActivitiesTable(
        IAnsiConsole console,
        MynatimeProfile profile,
        IEnumerable<ActivityItemWrapper> activities,
        Predicate<ActivityItemWrapper>? filter = null,
        Func<ActivityItemWrapper, string>? annotate = null)
    {
        var table = new Table().Border(TableBorder.Simple);
        if (annotate != null)
        {
            table.AddColumn(string.Empty);
        }

        table.AddColumn("Date");
        table.AddColumn("In");
        table.AddColumn("Out");
        table.AddColumn("Duration");
        table.AddColumn("Category");
        table.AddColumn("Comment");

        DateTime? lastDate = null;
        foreach (var entry in activities)
        {
            if (filter != null && !filter(entry))
            {
                continue;
            }

            var item = entry.Item;
            var actDate = item.DateStart ?? item.DateEnd;
            if (lastDate.HasValue && actDate.HasValue && actDate.Value.Date != lastDate.Value.Date)
            {
                table.AddEmptyRow();
            }

            lastDate = actDate ?? lastDate;
            var dateStr = item.DateStart?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) ?? string.Empty;
            var inStr = item.InAt.HasValue ? item.InAt.Value.ToString(@"hh\:mm") : string.Empty;
            var outStr = ActivityFormat.OutDisplay(item);
            var durationStr = ActivityFormat.DurationDisplay(item);

            string categoryMarkup;
            if (item.ActivityId == null)
            {
                categoryMarkup = string.Empty;
            }
            else
            {
                var catName = profile.Data?.GetActivityById(item.ActivityId)?.Name;
                categoryMarkup = catName != null
                    ? CliTheme.Tag(CliTheme.Category, catName)
                    : "[grey](unknown)[/]";
            }

            var dateCol = CliTheme.Tag(CliTheme.Timestamp, dateStr);
            var inCol = CliTheme.Tag(CliTheme.Timestamp, inStr);
            var outCol = CliTheme.Tag(CliTheme.Timestamp, outStr);
            var durationCol = CliTheme.Tag(CliTheme.Duration, durationStr);
            var commentCol = CliTheme.Tag(CliTheme.Comment, item.Comment ?? string.Empty);

            if (annotate != null)
            {
                table.AddRow(annotate(entry), dateCol, inCol, outCol, durationCol, categoryMarkup, commentCol);
            }
            else
            {
                table.AddRow(dateCol, inCol, outCol, durationCol, categoryMarkup, commentCol);
            }
        }

        if (table.Rows.Count > 0)
        {
            console.Write(table);
        }
        else
        {
            console.MarkupLine("  none");
        }
    }
}
