// Generated by Claude, 2026-05-17
namespace Mynatime.CLI;

using Mynatime.Client;
using System.Globalization;

internal static class ActivityFormat
{
    /// <summary>
    /// Returns a formatted duration string for an activity item.
    /// Uses the explicit Duration field if set, otherwise computes from InAt/OutAt.
    /// Returns empty string when neither is available.
    /// </summary>
    public static string DurationDisplay(NewActivityItemPage item)
    {
        if (item.Duration != null && decimal.TryParse(item.Duration, NumberStyles.Float, CultureInfo.InvariantCulture, out var hours))
        {
            return FormatSpan(TimeSpan.FromHours((double)hours));
        }

        if (item.InAt.HasValue && item.OutAt.HasValue)
        {
            var start = (item.DateStart ?? DateTime.MinValue) + item.InAt.Value;
            var end = (item.DateEnd ?? item.DateStart ?? DateTime.MinValue) + item.OutAt.Value;
            var span = end - start;
            if (span > TimeSpan.Zero)
            {
                return FormatSpan(span);
            }
        }

        return string.Empty;
    }

    /// <summary>
    /// Returns the Out time string, appending a "+Nd" suffix when the end date is after the start date.
    /// </summary>
    public static string OutDisplay(NewActivityItemPage item)
    {
        if (!item.OutAt.HasValue)
        {
            return string.Empty;
        }

        var timeStr = item.OutAt.Value.ToString(@"hh\:mm");
        if (item.DateStart.HasValue && item.DateEnd.HasValue && item.DateEnd.Value.Date > item.DateStart.Value.Date)
        {
            var days = (int)(item.DateEnd.Value.Date - item.DateStart.Value.Date).TotalDays;
            return timeStr + $" +{days}d";
        }

        return timeStr;
    }

    private static string FormatSpan(TimeSpan span)
        => $"{(int)span.TotalHours}:{span.Minutes:D2}";
}
