// Generated by Claude, 2026-05-17
namespace Mynatime.CLI;

using Spectre.Console;

/// <summary>
/// Markup color tokens for semantic value types, used consistently across all commands.
/// </summary>
internal static class CliTheme
{
    public const string Category      = "tan";
    public const string CategoryAlias = "#CD853F";
    public const string Timestamp     = "steelblue";
    public const string Duration      = "mediumpurple";
    public const string Comment       = "darkorange";
    public const string Chrome        = "grey";

    /// <summary>Wraps <paramref name="value"/> in a color tag, or returns empty string when value is null/empty.</summary>
    public static string Tag(string color, string? value)
        => string.IsNullOrEmpty(value) ? string.Empty : $"[{color}]{Markup.Escape(value)}[/]";
}
