// Generated by Claude, 2026-05-17
namespace Mynatime.CLI;

using System.Net.Http;
using System.Reflection;
using System.Text.Json;

internal static class UpdateChecker
{
    private const string Repo = "sandrock/mynatime";

    public static string? GetCurrentVersion()
        => Assembly.GetEntryAssembly()
            ?.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
            ?.InformationalVersion;

    public static async Task<string?> GetLatestTagAsync()
    {
        try
        {
            using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(3) };
            http.DefaultRequestHeaders.UserAgent.ParseAdd("mynatime-cli");
            var json = await http.GetStringAsync($"https://api.github.com/repos/{Repo}/releases/latest");
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("tag_name", out var tagEl))
            {
                return tagEl.GetString();
            }
        }
        catch { }

        return null;
    }

    /// <summary>
    /// Returns true when latestTag represents a version strictly greater than currentVersion.
    /// Pre-release suffixes in currentVersion are stripped before comparison so dev builds
    /// ahead of a tag do not trigger a false positive.
    /// </summary>
    public static bool IsNewer(string? latestTag, string? currentVersion)
    {
        if (latestTag == null || currentVersion == null)
        {
            return false;
        }

        var latestStr = latestTag.TrimStart('v');
        var dashIdx = currentVersion.IndexOf('-');
        var currentBase = dashIdx >= 0 ? currentVersion[..dashIdx] : currentVersion;

        return Version.TryParse(latestStr, out var latest)
            && Version.TryParse(currentBase, out var current)
            && latest > current;
    }
}
