// Generated by Claude, 2026-05-18
namespace Mynatime.CLI;

using Spectre.Console;
using System.Diagnostics;

/// <summary>
/// Opens a Mynatime-related URL in the default browser.
/// </summary>
public sealed class WebCommand : Command
{
    private const string UrlDocs     = "https://sandrock.github.io/mynatime/";
    private const string UrlReleases = "https://github.com/sandrock/mynatime/releases";
    private const string UrlIssues   = "https://github.com/sandrock/mynatime/issues";
    private const string UrlGitHub   = "https://github.com/sandrock/mynatime";

    public static string[] Args { get; } = new string[] { "web", };

    private string targetUrl = UrlDocs;

    public WebCommand(IConsoleApp app, IAnsiConsole console)
        : base(app, console)
    {
        this.AutoLoadProfile = false;
    }

    public override CommandDescription Describe()
    {
        var describe = base.Describe();
        describe.Title = "Web";
        describe.AddCommandPattern(Args[0],              "opens the documentation website");
        describe.AddCommandPattern(Args[0] + " releases", "opens the releases page");
        describe.AddCommandPattern(Args[0] + " issues",   "opens the issues page");
        describe.AddCommandPattern(Args[0] + " github",   "opens the GitHub repository");
        return describe;
    }

    public override bool MatchArg(string arg)
    {
        return ConsoleApp.MatchArg(arg, Args);
    }

    public override bool ParseArgs(IConsoleApp app, string[] args, out int consumedArgs, out Command? command)
    {
        var i = -1;
        if (++i >= args.Length || !this.MatchArg(args[i]))
        {
            goto error;
        }

        if (++i < args.Length)
        {
            var sub = args[i];
            if (ConsoleApp.MatchArg(sub, "releases", "release", "update", "updates"))
            {
                this.targetUrl = UrlReleases;
            }
            else if (ConsoleApp.MatchArg(sub, "issues", "issue", "bugs", "bug"))
            {
                this.targetUrl = UrlIssues;
            }
            else if (ConsoleApp.MatchArg(sub, "github", "repo"))
            {
                this.targetUrl = UrlGitHub;
            }
            else
            {
                goto error;
            }
        }

        consumedArgs = args.Length;
        command = this;
        return true;

        error:
        consumedArgs = 0;
        command = null;
        return false;
    }

    public override Task Run()
    {
        this.Console.WriteLine("Opening: " + this.targetUrl);
        try
        {
            Process.Start(new ProcessStartInfo(this.targetUrl) { UseShellExecute = true });
        }
        catch (Exception ex)
        {
            this.Console.MarkupLine("[red]Could not open browser: " + Markup.Escape(ex.Message) + "[/]");
            this.Console.WriteLine("Please open manually: " + this.targetUrl);
        }

        return Task.CompletedTask;
    }
}
