// Generated by Claude Sonnet 4.6 on 2026-05-15

namespace Mynatime.CLI.Tests;

using Moq;
using Mynatime.Infrastructure;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Xunit;

public class ProfileStatusCommandTests
{
    private MockRepository mocks = new MockRepository(MockBehavior.Strict);

    public static IEnumerable<object[]> ValidArgs()
    {
        yield return new object[] { "pro",      "status", };
        yield return new object[] { "pro",      "sta",    };
        yield return new object[] { "profile",  "status", };
        yield return new object[] { "profiles", "status", };
        yield return new object[] { "Profile",  "Status", };
    }

    public static IEnumerable<object[]> InvalidArgs()
    {
        yield return new object[] { "pro",  "list",   };
        yield return new object[] { "pro",  "add",    };
        yield return new object[] { "act",  "status", };
        yield return new object[] { "status",         };
    }

    [Theory, MemberData(nameof(ValidArgs))]
    public void ParseArgs_Valid(string arg0, string arg1)
    {
        var app = MakeApp();
        var target = new ProfileStatusCommand(app.Object);
        var result = target.ParseArgs(app.Object, new[] { arg0, arg1 }, out int consumed, out Command? command);
        Assert.True(result);
        Assert.NotNull(command);
        Assert.Equal(2, consumed);
    }

    [Theory, MemberData(nameof(InvalidArgs))]
    public void ParseArgs_Invalid(params string[] args)
    {
        var app = MakeApp();
        var target = new ProfileStatusCommand(app.Object);
        var result = target.ParseArgs(app.Object, args, out int consumed, out Command? command);
        Assert.False(result);
        Assert.Null(command);
    }

    [Fact]
    public async Task Run_NoProfile_PrintsMessage()
    {
        var app = MakeApp(profile: null);
        var target = new ProfileStatusCommand(app.Object);

        var output = await CaptureRun(target);

        Assert.Contains("No profile loaded", output);
    }

    [Fact]
    public async Task Run_MinimalProfile_ShowsFileAndUsername()
    {
        var profile = new MynatimeProfile();
        profile.LoginUsername = "user@example.com";
        var app = MakeApp(profile);
        var target = new ProfileStatusCommand(app.Object);

        var output = await CaptureRun(target);

        Assert.Contains("user@example.com", output);
        Assert.Contains("(unsaved)", output);
        Assert.Contains("none", output);       // session
    }

    [Fact]
    public async Task Run_WithIdentity_ShowsNameAndRoles()
    {
        var profile = new MynatimeProfile();
        profile.LoginUsername = "user@example.com";
        profile.UserId = "12345";
        profile.Identity = new JObject
        {
            ["email"]     = "user@example.com",
            ["name"]      = "Antoine SOTTIAU",
            ["roles"]     = new JArray("ROLE_USER_MT", "ROLE_MANAGER_MT"),
        };
        var app = MakeApp(profile);
        var target = new ProfileStatusCommand(app.Object);

        var output = await CaptureRun(target);

        Assert.Contains("Antoine SOTTIAU", output);
        Assert.Contains("12345", output);
        Assert.Contains("ROLE_USER_MT", output);
        Assert.Contains("ROLE_MANAGER_MT", output);
    }

    [Fact]
    public async Task Run_WithCookies_ShowsActiveSession()
    {
        var profile = new MynatimeProfile();
        profile.LoginUsername = "user@example.com";
        profile.Cookies = new JArray(
            new JObject { ["Name"] = "PHPSESSID", ["Value"] = "abc" },
            new JObject { ["Name"] = "REMEMBERME", ["Value"] = "xyz" });
        var app = MakeApp(profile);
        var target = new ProfileStatusCommand(app.Object);

        var output = await CaptureRun(target);

        Assert.Contains("active", output);
        Assert.Contains("2 cookies", output);
    }

    [Fact]
    public async Task Run_WithCategories_ShowsCountAndDate()
    {
        var profile = new MynatimeProfile();
        profile.LoginUsername = "user@example.com";
        profile.Data!.ActivityCategories!.Add(new MynatimeProfileDataActivityCategory("1", "Internal"));
        profile.Data.ActivityCategories.Add(new MynatimeProfileDataActivityCategory("2", "Project"));
        profile.Data.ActivityCategories.LastUpdated = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc);
        var app = MakeApp(profile);
        var target = new ProfileStatusCommand(app.Object);

        var output = await CaptureRun(target);

        Assert.Contains("2 categories", output);
        Assert.Contains("2026-04-01", output);
    }

    [Fact]
    public async Task Run_WithPendingAndCommits_ShowsCounts()
    {
        var profile = new MynatimeProfile();
        profile.LoginUsername = "user@example.com";
        profile.Transaction!.Add(new MynatimeProfileTransactionItem());
        profile.Transaction.Add(new MynatimeProfileTransactionItem());
        profile.Commits!.Add(new MynatimeProfileTransactionItem());
        var app = MakeApp(profile);
        var target = new ProfileStatusCommand(app.Object);

        var output = await CaptureRun(target);

        Assert.Contains("2 items", output);  // pending
        Assert.Contains("1 item",  output);  // commits (singular)
    }

    private Mock<IConsoleApp> MakeApp(MynatimeProfile? profile = null)
    {
        var mock = this.mocks.Create<IConsoleApp>();
        mock.SetupGet(x => x.CurrentProfile).Returns(profile);
        return mock;
    }

    private static async Task<string> CaptureRun(Command command)
    {
        var original = Console.Out;
        using var writer = new StringWriter();
        Console.SetOut(writer);
        try
        {
            await command.Run();
        }
        finally
        {
            Console.SetOut(original);
        }

        return writer.ToString();
    }
}
